velodyne_transform_node:
    ros__parameters:
        calibration: VLP16db.yaml
        model: VLP16
        min_range: 0.9
        max_range: 130.0
        view_direction: 0.0
        view_width: 3.14159  # Ï€ radians = 180 degrees (front view: -90 to +90 degrees)
        fixed_frame: ""
        target_frame: ""
        organize_cloud: true
